root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o ./bin/main"
# Customize binary, can setup environment variables when run your app. eg: APP_ENV=dev APP_USER=air ./bin/main
full_bin = "./bin/main"
# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
# args_bin = ["hello", "world"]
include_ext = ["go", "templ", "css"]
exclude_dir = ["assets", "tmp", "testdata", "vendor", "web/node_modules"]
exclude_regex = [".*_templ.go"]
log = "air.log"

[log]
time = false
main_only = false
