name: Prepare the website
run-name: prepare the website
on: 
  pull_request_target:
    branches:
      - main
    types: [closed]
      
jobs:
  png-to-webp:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup cwebp
        run: |
          pwd
          sudo apt-get install libjpeg-dev libpng-dev
          echo "wget webp"
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-linux-x86-64.tar.gz
          
          echo "unzipping"
          tar xzvf libwebp-1.4.0-linux-x86-64.tar.gz

          echo "moving cwebp bin to gh workspace"
          cd libwebp-1.4.0-linux-x86-64/bin
          mv cwebp ${{ github.workspace }}
          cd ../..

          echo "removing the tar ball and the unzipped folder"
          rm -rf libwebp-1.4.0-linux-x86-64
          rm -rf libwebp-1.4.0-linux-x86-64.tar.gz

          echo "moving cwebp to /bin"
          sudo mv cwebp /bin
          ls

      - name: Converting to webp
        run: |
          ./bin/towebp-l ./web/static/media/images/gallery 256000
          ls

      - name: Amend the last commit
        run: | 
          git config --global user.email "harmeepatel@gmail.com"
          git config --global user.name "harmeepatel"
          git add .
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"

  generate-templ:
    needs: png-to-webp
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2' # The Go version to download (if necessary) and use.
      - name: install templ
        run: |
          sudo apt-get install tree
          go mod tidy
          go install github.com/a-h/templ/cmd/templ@latest
          templ version
          templ generate
          tree

      - name: Amend the last commit
        run: |
          git config --global user.email "harmeepatel@gmail.com"
          git config --global user.name "harmeepatel"
          git add .
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"

  generate-html:
    needs: [png-to-webp, generate-templ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2' # The Go version to download (if necessary) and use.
      - name: go run main.go
        run: |
          git pull --rebase
          go mod tidy
          go run main.go

      - name: Amend the last commit
        run: |
          git config --global user.email "harmeepatel@gmail.com"
          git config --global user.name "harmeepatel"
          git pull --rebase
          git add .
          git commit -a -amend --no-edit
          git push --force-with-lease
          echo "Complete"
