name: Prepare the website
run-name: prepare the website
on: 
  pull_request_target:
    branches:
      - main
    types: [closed]
      
jobs:
  png-to-webp:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup cwebp
        run: |
          pwd
          sudo apt-get install libjpeg-dev libpng-dev
          echo "wget webp"
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0-linux-x86-64.tar.gz
          
          echo "unzipping"
          tar xzvf libwebp-1.4.0-linux-x86-64.tar.gz

          echo "moving cwebp bin to gh workspace"
          cd libwebp-1.4.0-linux-x86-64/bin
          mv cwebp ${{ github.workspace }}
          cd ../..

          echo "removing the tar ball and the unzipped folder"
          rm -rf libwebp-1.4.0-linux-x86-64
          rm -rf libwebp-1.4.0-linux-x86-64.tar.gz

          echo "moving cwebp to /bin"
          sudo mv cwebp /bin
          ls

      - name: Converting to webp
        run: |
          ./bin/towebp-l ./static/media/images/gallery 256000
          ls

      - name: Amend the last commit
        run: | 
          git config --global user.email "harmeepatel@gmail.com"
          git config --global user.name "harmeepatel"
          git add .
          git commit -v -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"

  generate-templ:
    needs: png-to-webp
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2' # The Go version to download (if necessary) and use.
      - name: Pull the converted webp images
        run: |
          git pull --rebase -f

      - name: See work tree
        run: |
          sudo apt-get install tree
          tree

      - name: Main branch cleanup
        run: |
          rm -f ./index.html ./blog.html ./photos.html
          find ./ -name '*_templ.go' -delete

      - name: See work tree
        run: |
          tree

      - name: Go setup
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          
      - name: Generating go files from templ
        run: |
          templ version
          templ generate
          go mod tidy

      - name: See work tree
        run: |
          tree

      - name: Generating html files
        run: |
          go run main.go

      - name: See work tree
        run: |
          tree

      - name: Cleanup main branch
        run: |
          rm -rf ./bin ./dist ./web go.mod go.sum main.go utils.go

      - name: Amend the last commit
        run: |
          git config --global user.email "harmeepatel@gmail.com"
          git config --global user.name "harmeepatel"
          git add .
          git commit -v -a --amend --no-edit
          git push --force-with-lease origin main
          echo "Complete"
